server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.18:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    elasticsearch:
      cluster-nodes: 192.168.3.18:9300
      cluster-name: my-application

  mvc:
    static-path-pattern: /**

  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: static/**

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

